$files = @(
    "main.lua",
    "ui_lib.lua",
    "src/shared/Cleaner.lua",
    "src/shared/ErrorHandler.lua",
    "src/shared/Services.lua",
    "src/shared/Globals.lua",
    "src/features/combat/Aimbot.lua",
    "src/features/combat/TriggerBot.lua",
    "src/features/combat/Hitbox.lua",
    "src/features/movement/BunnyHop.lua",
    "src/features/skins/Skinchanger.lua",
    "src/features/visuals/ESP.lua",
    "src/features/visuals/Chams.lua",
    "src/features/visuals/KillEffects.lua",
    "src/features/visuals/WorldEffects.lua"
)

function Convert-ToLuaLongString {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Text
    )

    for ($level = 0; $level -lt 16; $level++) {
        $eq = "=" * $level
        $open = "[" + $eq + "["
        $close = "]" + $eq + "]"
        if (-not $Text.Contains($close)) {
            return $open + $Text + $close
        }
    }

    throw "Unable to encode file contents as a Lua long string."
}

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("-- generated by build_bundle.ps1")
[void]$builder.AppendLine("local moduleSources = {")

foreach ($file in $files) {
    $normalized = $file.Replace("\", "/")
    $content = Get-Content -Raw -LiteralPath $file
    $encoded = Convert-ToLuaLongString -Text $content
    [void]$builder.AppendLine("    [""$normalized""] = $encoded,")
}

[void]$builder.AppendLine("}")
[void]$builder.AppendLine("local compile = loadstring or load")
[void]$builder.AppendLine("assert(type(compile) == ""function"", ""No loadstring/load available"")")
[void]$builder.AppendLine("local mainChunk = assert(compile(moduleSources[""main.lua""], ""@bundle/main.lua""))")
[void]$builder.AppendLine("return mainChunk({")
[void]$builder.AppendLine("    moduleSources = moduleSources,")
[void]$builder.AppendLine("})")

Set-Content -LiteralPath "bundle.lua" -Value $builder.ToString() -NoNewline
